# Generated by Django 3.2.13 on 2022-06-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=140)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('genre', models.CharField(max_length=140)),
                ('instruments', models.CharField(max_length=140)),
                ('primary_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.artist')),
            ],
        ),
        migrations.CreateModel(
            name='RecordCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.recordcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.artist')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.producer')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.userprofile'),
        ),
        migrations.AddField(
            model_name='album',
            name='primary_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.producer'),
        ),
    ]
